options:
  substitution_option: 'ALLOW_LOOSE'
  env:
    - CLOUDSDK_COMPUTE_ZONE=${_ZONE}
    - CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}
    - ENV=${_ENV}
steps:
  - id: 'patch-k8s-config'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['-c','find k8s -type f | xargs sed -i -e "s/PROJECT_ID/$PROJECT_ID/g" -e "s/ENV/${_ENV}/g"']
  - id: 'render-grpc-server'
    name: gcr.io/$PROJECT_ID/skaffold:alpha
    args: ['render', '-f=skaffold.yaml', '--output=k8s-grpc-server.yaml']
    waitFor: ['-']
  - id: 'copy-grpc-server-render'
    name: gcr.io/cloud-builders/gsutil
    args: ['cp','k8s-grpc-server.yaml','gs://mad-demo-k8s/']
    waitFor: ['render-grpc-server']
timeout: 400s
tags: ['grpc-server-render']
