options:
  substitution_option: 'ALLOW_LOOSE'
  env:
    - CLOUDSDK_COMPUTE_ZONE=${_ZONE}
    - CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}
    - ENV=${_ENV}
    - PROJECT_ID=$PROJECT_ID
steps:
  - id: 'build-grpc-server'
    name: gcr.io/$PROJECT_ID/skaffold:alpha
    args: ['build', '-f=skaffold.yaml']
timeout: 300s
tags: ['grpc-server-build','${_ENV}']
